---

- name: Create an instance on AWS
  hosts: localhost
  gather_facts: False
  vars:
    instance_type: m4.xlarge
    security_group: Enterprise 2
  tasks:
    - name: Launch instance on AWS
      ec2:
        key_name: "{{ key_name }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes
        region: "{{ region }}"
        vpc_subnet_id: subnet-25d4d55d
        assign_public_ip: yes
        count: 1
        instance_tags:
          Name: Ansible-test
        volumes:
          - device_name: /dev/sdb
            volume_type: gp2
            volume_size: 16
      register: ec2

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 122
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"
